# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=pages.models.image_upload_handler)),
            ],
        ),
        migrations.CreateModel(
            name='MiscFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=pages.models.misc_upload_handler)),
            ],
        ),
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=pages.models.pdf_upload_handler)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=pages.models.text_upload_handler)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Show')),
            ],
        ),
        migrations.AddField(
            model_name='pdffile',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Show'),
        ),
        migrations.AddField(
            model_name='miscfile',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Show'),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Show'),
        ),
    ]
